# Generated by Django 3.2.10 on 2022-08-24 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_student_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
