# Generated by Django 3.2.10 on 2022-08-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_student_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
